#!/usr/bin/env sh
set -x
device=$(xinput |grep -i "Touchpad" | cut -d= -f 2 |head -c 2)
state=$(xinput list-props "$device" | grep "Device Enabled" | grep -o "[01]$")

if [ $state = '1' ]; then
  xinput --disable $device
else
  xinput --enable $device
fi